// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AccountServiceChangePasswordData,
  AccountServiceChangePasswordResponses,
  AccountServiceGetAdminMeData,
  AccountServiceGetAdminMeResponses,
  AccountServiceRefreshTokenData,
  AccountServiceRefreshTokenResponses,
  AccountServiceSignInByEmailData,
  AccountServiceSignInByEmailResponses,
  AccountServiceSignOutData,
  AccountServiceSignOutResponses,
  AccountServiceUpdateProfileData,
  AccountServiceUpdateProfileResponses,
  CreatorServiceListCreatorsData,
  CreatorServiceListCreatorsResponses,
  PresetThemeServiceCreatePresetThemeData,
  PresetThemeServiceCreatePresetThemeResponses,
  PresetThemeServiceDeletePresetThemeData,
  PresetThemeServiceDeletePresetThemeResponses,
  PresetThemeServiceGetPresetThemeData,
  PresetThemeServiceGetPresetThemeResponses,
  PresetThemeServiceListPresetThemesData,
  PresetThemeServiceListPresetThemesResponses,
  PresetThemeServiceUpdatePresetThemeData,
  PresetThemeServiceUpdatePresetThemeResponses,
  SiteServiceListSitesData,
  SiteServiceListSitesResponses,
  SuperAdminServiceCreateSuperAdminData,
  SuperAdminServiceCreateSuperAdminResponses,
  SuperAdminServiceDeleteSuperAdminData,
  SuperAdminServiceDeleteSuperAdminResponses,
  SuperAdminServiceGetSuperAdminData,
  SuperAdminServiceGetSuperAdminResponses,
  SuperAdminServiceListSuperAdminData,
  SuperAdminServiceListSuperAdminResponses,
  SuperAdminServiceUpdateSuperAdminData,
  SuperAdminServiceUpdateSuperAdminResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const accountServiceChangePassword = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AccountServiceChangePasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountServiceChangePasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/account/change_password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const accountServiceGetAdminMe = <ThrowOnError extends boolean = false>(
  options?: Options<AccountServiceGetAdminMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountServiceGetAdminMeResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/account/me',
    ...options,
  });
};

export const accountServiceRefreshToken = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AccountServiceRefreshTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountServiceRefreshTokenResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/account/refresh_token',
    ...options,
  });
};

export const accountServiceSignInByEmail = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AccountServiceSignInByEmailData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountServiceSignInByEmailResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/account/sign_in_by_email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const accountServiceSignOut = <ThrowOnError extends boolean = false>(
  options?: Options<AccountServiceSignOutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountServiceSignOutResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/account/sign_out',
    ...options,
  });
};

export const accountServiceUpdateProfile = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AccountServiceUpdateProfileData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountServiceUpdateProfileResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/account/update_profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const creatorServiceListCreators = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CreatorServiceListCreatorsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreatorServiceListCreatorsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/creator/list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const presetThemeServiceCreatePresetTheme = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PresetThemeServiceCreatePresetThemeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PresetThemeServiceCreatePresetThemeResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/preset_theme/create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const presetThemeServiceDeletePresetTheme = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PresetThemeServiceDeletePresetThemeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PresetThemeServiceDeletePresetThemeResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/preset_theme/delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const presetThemeServiceGetPresetTheme = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PresetThemeServiceGetPresetThemeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PresetThemeServiceGetPresetThemeResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/preset_theme/get',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const presetThemeServiceListPresetThemes = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PresetThemeServiceListPresetThemesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PresetThemeServiceListPresetThemesResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/preset_theme/list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const presetThemeServiceUpdatePresetTheme = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PresetThemeServiceUpdatePresetThemeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PresetThemeServiceUpdatePresetThemeResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/preset_theme/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const siteServiceListSites = <ThrowOnError extends boolean = false>(
  options?: Options<SiteServiceListSitesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SiteServiceListSitesResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/site/list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const superAdminServiceCreateSuperAdmin = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperAdminServiceCreateSuperAdminData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SuperAdminServiceCreateSuperAdminResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/super_admin/create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const superAdminServiceDeleteSuperAdmin = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperAdminServiceDeleteSuperAdminData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SuperAdminServiceDeleteSuperAdminResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/super_admin/delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const superAdminServiceGetSuperAdmin = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperAdminServiceGetSuperAdminData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SuperAdminServiceGetSuperAdminResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/super_admin/get',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const superAdminServiceListSuperAdmin = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperAdminServiceListSuperAdminData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SuperAdminServiceListSuperAdminResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/super_admin/list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const superAdminServiceUpdateSuperAdmin = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperAdminServiceUpdateSuperAdminData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SuperAdminServiceUpdateSuperAdminResponses,
    unknown,
    ThrowOnError
  >({
    url: '/platform_admin_api/v1/super_admin/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};
