// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type BaseIdData = {
  id?: string;
};

export type BaseIdRespBody = {
  code?: number;
  msg?: string;
  data?: BaseIdData;
};

export type BaseMsgRespBody = {
  code?: number;
  msg?: string;
};

export type ChangePasswordReqBody = {
  old_password?: string;
  new_password?: string;
};

export type CreatePresetThemeReqBody = {
  name?: string;
  description?: string;
  category?: string;
  config?: string;
  primary_color?: string;
  accent_color?: string;
  secondary_color?: string;
  border_color?: string;
  published?: boolean;
};

export type CreateSuperAdminReqBody = {
  name?: string;
  email?: string;
  password?: string;
};

export type CreatorInfo = {
  id?: string;
  display_name?: string;
  email?: string;
  avatar?: string;
  status?: string;
  created_at?: string;
  updated_at?: string;
};

export type GetAdminRespBody = {
  code?: number;
  msg?: string;
  data?: SuperAdminInfo;
};

export type GetPresetThemeData = {
  preset_theme?: PresetThemeInfo;
};

export type GetPresetThemeRespBody = {
  code?: number;
  msg?: string;
  data?: GetPresetThemeData;
};

export type GetSuperAdminData = {
  super_admin?: SuperAdminInfo;
};

export type GetSuperAdminRespBody = {
  code?: number;
  msg?: string;
  data?: GetSuperAdminData;
};

export type IdReqBody = {
  id?: string;
};

export type ListCreatorsData = {
  creators?: Array<CreatorInfo>;
  total?: number;
};

export type ListCreatorsReqBody = {
  page?: number;
  page_size?: number;
  display_name?: string;
  email?: string;
};

export type ListCreatorsRespBody = {
  code?: number;
  msg?: string;
  data?: ListCreatorsData;
};

export type ListPresetThemesData = {
  preset_themes?: Array<PresetThemeInfo>;
  total?: number;
};

export type ListPresetThemesReqBody = {
  page?: number;
  page_size?: number;
  name?: string;
};

export type ListPresetThemesRespBody = {
  code?: number;
  msg?: string;
  data?: ListPresetThemesData;
};

export type ListSitesData = {
  sites?: Array<SiteInfo>;
  total?: number;
};

export type ListSitesReqBody = {
  page?: number;
  page_size?: number;
  name?: string;
  description?: string;
  subdomain?: string;
};

export type ListSitesRespBody = {
  code?: number;
  msg?: string;
  data?: ListSitesData;
};

export type ListSuperAdminData = {
  super_admins?: Array<SuperAdminInfo>;
  total?: number;
};

export type ListSuperAdminReqBody = {
  page?: number;
  page_size?: number;
  name?: string;
  email?: string;
};

export type ListSuperAdminRespBody = {
  code?: number;
  msg?: string;
  data?: ListSuperAdminData;
};

export type PresetThemeInfo = {
  id?: string;
  name?: string;
  description?: string;
  category?: string;
  config?: ThemeConfig;
  primary_color?: string;
  accent_color?: string;
  secondary_color?: string;
  border_color?: string;
  created_at?: string;
  updated_at?: string;
  published?: boolean;
};

export type SignInByEmailReqBody = {
  email?: string;
  password?: string;
  captcha_token?: string;
  device_fingerprint?: string;
};

export type SignInSuccessRespBody = {
  code?: number;
  msg?: string;
  data?: TokenInfo;
};

export type SiteInfo = {
  id?: string;
  name?: string;
  description?: string;
  subdomain?: string;
  custom_domain?: string;
  status?: string;
  is_private?: boolean;
  white_label?: boolean;
  max_members?: number;
  stat?: SiteStatInfo;
  creator_id?: string;
  created_at?: string;
  updated_at?: string;
};

export type SiteStatInfo = {
  member_count?: number;
  post_count?: number;
  blog_count?: number;
  event_count?: number;
  course_count?: number;
  space_count?: number;
};

export type SuperAdminInfo = {
  id?: string;
  name?: string;
  email?: string;
  created_at?: string;
  updated_at?: string;
};

export type ThemeConfig = {
  light?: ThemeStyle;
  dark?: ThemeStyle;
};

export type ThemeStyle = {
  background?: string;
  foreground?: string;
  card?: string;
  card_foreground?: string;
  popover?: string;
  popover_foreground?: string;
  primary?: string;
  primary_foreground?: string;
  secondary?: string;
  secondary_foreground?: string;
  muted?: string;
  muted_foreground?: string;
  accent?: string;
  accent_foreground?: string;
  destructive?: string;
  border?: string;
  input?: string;
  ring?: string;
  chart_1?: string;
  chart_2?: string;
  chart_3?: string;
  chart_4?: string;
  chart_5?: string;
  sidebar?: string;
  sidebar_foreground?: string;
  sidebar_primary?: string;
  sidebar_primary_foreground?: string;
  sidebar_accent?: string;
  sidebar_accent_foreground?: string;
  sidebar_border?: string;
  sidebar_ring?: string;
  font_sans?: string;
  font_serif?: string;
  font_mono?: string;
  radius?: string;
  shadow_color?: string;
  shadow_opacity?: string;
  shadow_blur?: string;
  shadow_spread?: string;
  shadow_offset_x?: string;
  shadow_offset_y?: string;
  letter_spacing?: string;
  spacing?: string;
};

export type TokenInfo = {
  token?: string;
  expires_at?: string;
};

export type UpdatePresetThemeReqBody = {
  id?: string;
  name?: string;
  description?: string;
  category?: string;
  config?: string;
  primary_color?: string;
  accent_color?: string;
  secondary_color?: string;
  border_color?: string;
  published?: boolean;
};

export type UpdateProfileReqBody = {
  name?: string;
  email?: string;
};

export type UpdateSuperAdminReqBody = {
  id?: string;
  name?: string;
  email?: string;
  password?: string;
};

export type AccountServiceChangePasswordData = {
  body?: ChangePasswordReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/account/change_password';
};

export type AccountServiceChangePasswordResponses = {
  /**
   * Successful response
   */
  200: BaseMsgRespBody;
};

export type AccountServiceChangePasswordResponse =
  AccountServiceChangePasswordResponses[keyof AccountServiceChangePasswordResponses];

export type AccountServiceGetAdminMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/account/me';
};

export type AccountServiceGetAdminMeResponses = {
  /**
   * Successful response
   */
  200: GetAdminRespBody;
};

export type AccountServiceGetAdminMeResponse =
  AccountServiceGetAdminMeResponses[keyof AccountServiceGetAdminMeResponses];

export type AccountServiceRefreshTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/account/refresh_token';
};

export type AccountServiceRefreshTokenResponses = {
  /**
   * Successful response
   */
  200: SignInSuccessRespBody;
};

export type AccountServiceRefreshTokenResponse =
  AccountServiceRefreshTokenResponses[keyof AccountServiceRefreshTokenResponses];

export type AccountServiceSignInByEmailData = {
  body?: SignInByEmailReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/account/sign_in_by_email';
};

export type AccountServiceSignInByEmailResponses = {
  /**
   * Successful response
   */
  200: SignInSuccessRespBody;
};

export type AccountServiceSignInByEmailResponse =
  AccountServiceSignInByEmailResponses[keyof AccountServiceSignInByEmailResponses];

export type AccountServiceSignOutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/account/sign_out';
};

export type AccountServiceSignOutResponses = {
  /**
   * Successful response
   */
  200: BaseMsgRespBody;
};

export type AccountServiceSignOutResponse =
  AccountServiceSignOutResponses[keyof AccountServiceSignOutResponses];

export type AccountServiceUpdateProfileData = {
  body?: UpdateProfileReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/account/update_profile';
};

export type AccountServiceUpdateProfileResponses = {
  /**
   * Successful response
   */
  200: BaseMsgRespBody;
};

export type AccountServiceUpdateProfileResponse =
  AccountServiceUpdateProfileResponses[keyof AccountServiceUpdateProfileResponses];

export type CreatorServiceListCreatorsData = {
  body?: ListCreatorsReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/creator/list';
};

export type CreatorServiceListCreatorsResponses = {
  /**
   * Successful response
   */
  200: ListCreatorsRespBody;
};

export type CreatorServiceListCreatorsResponse =
  CreatorServiceListCreatorsResponses[keyof CreatorServiceListCreatorsResponses];

export type PresetThemeServiceCreatePresetThemeData = {
  body?: CreatePresetThemeReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/preset_theme/create';
};

export type PresetThemeServiceCreatePresetThemeResponses = {
  /**
   * Successful response
   */
  200: BaseIdRespBody;
};

export type PresetThemeServiceCreatePresetThemeResponse =
  PresetThemeServiceCreatePresetThemeResponses[keyof PresetThemeServiceCreatePresetThemeResponses];

export type PresetThemeServiceDeletePresetThemeData = {
  body?: IdReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/preset_theme/delete';
};

export type PresetThemeServiceDeletePresetThemeResponses = {
  /**
   * Successful response
   */
  200: BaseMsgRespBody;
};

export type PresetThemeServiceDeletePresetThemeResponse =
  PresetThemeServiceDeletePresetThemeResponses[keyof PresetThemeServiceDeletePresetThemeResponses];

export type PresetThemeServiceGetPresetThemeData = {
  body?: IdReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/preset_theme/get';
};

export type PresetThemeServiceGetPresetThemeResponses = {
  /**
   * Successful response
   */
  200: GetPresetThemeRespBody;
};

export type PresetThemeServiceGetPresetThemeResponse =
  PresetThemeServiceGetPresetThemeResponses[keyof PresetThemeServiceGetPresetThemeResponses];

export type PresetThemeServiceListPresetThemesData = {
  body?: ListPresetThemesReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/preset_theme/list';
};

export type PresetThemeServiceListPresetThemesResponses = {
  /**
   * Successful response
   */
  200: ListPresetThemesRespBody;
};

export type PresetThemeServiceListPresetThemesResponse =
  PresetThemeServiceListPresetThemesResponses[keyof PresetThemeServiceListPresetThemesResponses];

export type PresetThemeServiceUpdatePresetThemeData = {
  body?: UpdatePresetThemeReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/preset_theme/update';
};

export type PresetThemeServiceUpdatePresetThemeResponses = {
  /**
   * Successful response
   */
  200: BaseMsgRespBody;
};

export type PresetThemeServiceUpdatePresetThemeResponse =
  PresetThemeServiceUpdatePresetThemeResponses[keyof PresetThemeServiceUpdatePresetThemeResponses];

export type SiteServiceListSitesData = {
  body?: ListSitesReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/site/list';
};

export type SiteServiceListSitesResponses = {
  /**
   * Successful response
   */
  200: ListSitesRespBody;
};

export type SiteServiceListSitesResponse =
  SiteServiceListSitesResponses[keyof SiteServiceListSitesResponses];

export type SuperAdminServiceCreateSuperAdminData = {
  body?: CreateSuperAdminReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/super_admin/create';
};

export type SuperAdminServiceCreateSuperAdminResponses = {
  /**
   * Successful response
   */
  200: BaseIdRespBody;
};

export type SuperAdminServiceCreateSuperAdminResponse =
  SuperAdminServiceCreateSuperAdminResponses[keyof SuperAdminServiceCreateSuperAdminResponses];

export type SuperAdminServiceDeleteSuperAdminData = {
  body?: IdReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/super_admin/delete';
};

export type SuperAdminServiceDeleteSuperAdminResponses = {
  /**
   * Successful response
   */
  200: BaseMsgRespBody;
};

export type SuperAdminServiceDeleteSuperAdminResponse =
  SuperAdminServiceDeleteSuperAdminResponses[keyof SuperAdminServiceDeleteSuperAdminResponses];

export type SuperAdminServiceGetSuperAdminData = {
  body?: IdReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/super_admin/get';
};

export type SuperAdminServiceGetSuperAdminResponses = {
  /**
   * Successful response
   */
  200: GetSuperAdminRespBody;
};

export type SuperAdminServiceGetSuperAdminResponse =
  SuperAdminServiceGetSuperAdminResponses[keyof SuperAdminServiceGetSuperAdminResponses];

export type SuperAdminServiceListSuperAdminData = {
  body?: ListSuperAdminReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/super_admin/list';
};

export type SuperAdminServiceListSuperAdminResponses = {
  /**
   * Successful response
   */
  200: ListSuperAdminRespBody;
};

export type SuperAdminServiceListSuperAdminResponse =
  SuperAdminServiceListSuperAdminResponses[keyof SuperAdminServiceListSuperAdminResponses];

export type SuperAdminServiceUpdateSuperAdminData = {
  body?: UpdateSuperAdminReqBody;
  path?: never;
  query?: never;
  url: '/platform_admin_api/v1/super_admin/update';
};

export type SuperAdminServiceUpdateSuperAdminResponses = {
  /**
   * Successful response
   */
  200: BaseMsgRespBody;
};

export type SuperAdminServiceUpdateSuperAdminResponse =
  SuperAdminServiceUpdateSuperAdminResponses[keyof SuperAdminServiceUpdateSuperAdminResponses];
